### ISSUE TITLE
stderr: remote: Support for password authentication was removed on August 13, 2021.

### ISSUE THREAD

**Issue by HarrierPanels** [jenkinsci/git-push-plugin#63]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

AWS Linux

### Reproduction steps

Set up as instructed with the git username/password credentials

### Expected Results

Git push

### Actual Results

stderr: remote: Support for password authentication was removed on August 13, 2021.

**Comment by reda-alaoui** [comment]
This message is not produced by this plugin.
Probably a misconfiguration.

**Comment by HarrierPanels** [comment]
In full:
Started by user [User 1](http://ec2-....)
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/Test1
The recommended git tool is: NONE
using credential HarrierPanels
 > git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/Test1/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/HarrierPanels/sql.git # timeout=10
Fetching upstream changes from https://github.com/HarrierPanels/sql.git
 > git --version # timeout=10
 > git --version # 'git version 2.37.1'
using GIT_ASKPASS to set credentials HarrierPanels
 > git fetch --tags --force --progress -- https://github.com/HarrierPanels/sql.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
Checking out Revision 765a0957fe5d2fdb12af83ff38d47a0362650b32 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 765a0957fe5d2fdb12af83ff38d47a0362650b32 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D master # timeout=10
 > git checkout -b master 765a0957fe5d2fdb12af83ff38d47a0362650b32 # timeout=10
Commit message: "Test removal"
 > git rev-list --no-walk 765a0957fe5d2fdb12af83ff38d47a0362650b32 # timeout=10
The recommended git tool is: NONE
using credential HarrierPanels
Fetching upstream changes from https://github.com/HarrierPanels/sql.git
 > git --version # timeout=10
 > git --version # 'git version 2.37.1'
using GIT_ASKPASS to set credentials HarrierPanels
 > git fetch --tags --force --progress -- https://github.com/HarrierPanels/sql.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/master^{commit} # timeout=10
 > git remote # timeout=10
 > git config --get remote.origin.url # timeout=10
using GIT_ASKPASS to set credentials HarrierPanels
 > git merge 765a0957fe5d2fdb12af83ff38d47a0362650b32 # timeout=10
using GIT_ASKPASS to set credentials HarrierPanels
 > git push https://github.com/HarrierPanels/sql.git HEAD:master # timeout=10
ERROR: Failed to push to origin
io.jenkins.plugins.git_push.GitPushCommand$Failure: Failed to push to origin
	at io.jenkins.plugins.git_push.GitPushCommand.call(GitPushCommand.java:54)
	at io.jenkins.plugins.git_push.GitPush.perform(GitPush.java:79)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:47)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:816)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:765)
	at hudson.model.Build$BuildExecution.post2(Build.java:179)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:709)
	at hudson.model.Run.execute(Run.java:1924)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
	at hudson.model.ResourceController.execute(ResourceController.java:107)
	at hudson.model.Executor.run(Executor.java:449)
Caused by: hudson.plugins.git.GitException: Command "git push https://github.com/HarrierPanels/sql.git HEAD:master" returned status code 128:
stdout: 
stderr: remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/HarrierPanels/sql.git/'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2736)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2111)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:87)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:2827)
	at io.jenkins.plugins.git_push.GitPushCommand.call(GitPushCommand.java:50)
	... 10 more
Build step 'Git Push' marked build as failure
The recommended git tool is: NONE
using credential HarrierPanels
Finished: FAILURE

**Comment by HarrierPanels** [comment]
Works now with token instead of password. No errors, success, but still unable to push.

**Comment by sohail-coder** [comment]
Same here for me as well, unable to push to git.
